name: به في علم الاجتماع

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-new-files:
    runs-on: ubuntu-latest
    steps:
      - name: رمز الخروج
        uses: actions/checkout@v3

      - name: اكتشف الملفات الجديدة
        run: |
          git diff --name-status HEAD~1 HEAD | grep '^A' | awk '{print $2}' > new_files.txt
          if [ -s new_files.txt ]; then
            echo "ملفات جديدة تم اكتشافها:"
            cat new_files.txt
          else
            echo "لم يتم اكتشاف ملفات جديدة."
